language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
env:
  - CLIENT_DIR=client
  - SERVER_DIR=server
before_script:
  - cd $CLIENT_DIR && yarn install
script:
  - cd $CLIENT_DIR && yarn test
